In [3]:
import sqlalchemy as alch
import os 
from dotenv import load_dotenv

# Loading env variables
load_dotenv()
free_password = os.getenv("free_sql_pw")
free_user = os.getenv('free_sql_user')

In [5]:
import sqlalchemy as alch
import os 
from dotenv import load_dotenv

import pandas as pd

In [2]:
load_dotenv()

True

In [4]:
# Connection to database
dbName = "sql7600024"
connectionData=f"mysql+pymysql://{free_user}:{free_password}@sql7.freesqldatabase.com/sql7600024"
engine = alch.create_engine(connectionData)

In [7]:
players = pd.read_csv('../config/Data.csv')

In [10]:
players

,Country,League,Club,Player Names,Matches_Played,Substitution,Mins,Goals,xG,xG Per Avg Match,Shots,OnTarget,Shots Per Avg Match,On Target Per Avg Match,Year
0,Spain,La Liga,(BET),Juanmi Callejon,19,16,1849,11,6.62,0.34,48,20,2.47,1.03,2016
1,Spain,La Liga,(BAR),Antoine Griezmann,36,0,3129,16,11.86,0.36,88,41,2.67,1.24,2016
2,Spain,La Liga,(ATL),Luis Suarez,34,1,2940,28,23.21,0.75,120,57,3.88,1.84,2016
3,Spain,La Liga,(CAR),Ruben Castro,32,3,2842,13,14.06,0.47,117,42,3.91,1.40,2016
4,Spain,La Liga,(VAL),Kevin Gameiro,21,10,1745,13,10.65,0.58,50,23,2.72,1.25,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,Netherlands,Eredivisie,(UTR),Gyrano Kerk,24,0,2155,10,7.49,0.33,50,18,2.20,0.79,2020
656,Netherlands,Eredivisie,(AJA),Quincy Promes,18,2,1573,12,9.77,0.59,56,30,3.38,1.81,2020
657,Netherlands,Eredivisie,(PSV),Denzel Dumfries,25,0,2363,7,5.72,0.23,45,14,1.81,0.56,2020
658,Netherlands,Eredivisie,None,Cyriel Dessers,26,0,2461,15,14.51,0.56,84,43,3.24,1.66,2020
659,Netherlands,Eredivisie,(PSV),Cody Gakpo,14,11,1557,7,4.43,0.27,38,15,2.32,0.92,2020

In [12]:
players.to_sql('Players', if_exists = 'replace', con = engine, index = False)

ProgrammingError: (pymysql.err.ProgrammingError) (1166, "Incorrect column name 'Substitution '")
[SQL:
CREATE TABLE `Players` (
	`Country` TEXT,
	`League` TEXT,
	`Club` TEXT,
	`Player Names` TEXT,
	`Matches_Played` BIGINT,
	`Substitution ` BIGINT,
	`Mins` BIGINT,
	`Goals` BIGINT,
	`xG` FLOAT(53),
	`xG Per Avg Match` FLOAT(53),
	`Shots` BIGINT,
	`OnTarget` BIGINT,
	`Shots Per Avg Match` FLOAT(53),
	`On Target Per Avg Match` FLOAT(53),
	`Year` BIGINT
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)

In [13]:
csv_file = pd.read_csv('/Users/gerardrius/Downloads/linkedin.csv')

In [15]:
csv_file.to_sql('Linkedin', if_exists = 'replace', con = engine, index = False)

237